<?php require_once './templates/header.phtml' ?>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Producto</th>
            <th>Nombre Categoria</th>
            <th>id Categoria</th>        
        </tr>
    </thead>


    <?php foreach($pedidos as $pedido): ?>
        
 
        
        <tbody>
            <tr>
                <td><?= $pedido->id_producto ?></td>                    
                <td><?= $pedido->producto ?></td>
                <td><?= $pedido->nombre_categoria ?></td>
                <td><?= $pedido->categoria ?></td>

            </tr>
        </tbody>
    <?php endforeach ?>

</table>



<?php require_once './templates/footer.phtml' ?>