<?php require_once './templates/header.phtml' ?>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>id</th>
            <th>producto</th>
            <th>id_categoria</th>
            <th>Detalle Producto</th>           
        </tr>
    </thead>


    <?php foreach($pedidos as $pedido): ?>
        
 
        
        <tbody>
            <tr>
                <td><?= $pedido->id_producto ?></td>                    
                <td><?= $pedido->producto ?></td> 
                <td><?= $pedido->categoria ?></td>
                <td><a href="detailProduct/<?= $pedido->id_producto?>" >Detalle</a></td>   
                <td><a href="delete/<?= $pedido->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
                <td><a href="edit/">Editar</a></td>                      
            </tr>
        </tbody>
    <?php endforeach ?>

</table>



<?php require_once './templates/footer.phtml' ?>