<?php require_once './templates/header.phtml' ?>

<form method="post" action="addProduct">
    <label for="">Ingrese el producto que desea</label>
    <input type="text" name="nombre_producto" id="nombre_producto">
    <button type="submit">AGREGAR</button>
    
</form>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>id producto</th>
            <th>Nombre producto</th>
            <th>Detalle producto</th>    
        </tr>
    </thead>
    
    
    <?php foreach($productos as $producto): ?>
              
        <tbody>
            <tr>
                <td><?= $producto->id_producto ?></td>                    
                <td><?= $producto->nombre_producto ?></td> 
                <td><a href="detailProduct/<?= $producto->id_producto?>" ><?= $producto->nombre_producto ?></a></td>
                <td><a href="deleteProduct/<?= $producto->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a></td>
                <td><a href="editProduct/<?= $producto->id_producto ?>" type="button" class='btn btn-danger ml-auto'>Editar</a></td>


            </tr>
        </tbody>
        <?php endforeach ?>
        
    </table>
    
    
<?php require_once './templates/footer.phtml' ?>